# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # For pnpm monorepos, use npm ecosystem
    directory: "/" # Root package.json

  # Apps directory packages
  - package-ecosystem: "npm"
    directory: "/apps/demo"

  - package-ecosystem: "npm"
    directory: "/apps/demo-react-native"

  - package-ecosystem: "npm"
    directory: "/apps/storybook"

  - package-ecosystem: "npm"
    directory: "/apps/web"

  # Packages directory
  - package-ecosystem: "npm"
    directory: "/packages/database"

  - package-ecosystem: "npm"
    directory: "/packages/lib"

  - package-ecosystem: "npm"
    directory: "/packages/types"

  - package-ecosystem: "npm"
    directory: "/packages/config-eslint"

  - package-ecosystem: "npm"
    directory: "/packages/config-prettier"

  - package-ecosystem: "npm"
    directory: "/packages/config-typescript"

  - package-ecosystem: "npm"
    directory: "/packages/js-core"

  - package-ecosystem: "npm"
    directory: "/packages/surveys"

  - package-ecosystem: "npm"
    directory: "/packages/logger"

  - package-ecosystem: "npm"
    directory: "/packages/js"

  - package-ecosystem: "npm"
    directory: "/packages/react-native"

  - package-ecosystem: "npm"
    directory: "/packages/vite-plugins"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
